import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding casting calls...');

  const castingCalls = [
    // Detroit casting call for auto-submission testing
    {
      title: 'Lead Role - Independent Feature Film',
      production: 'Motor City Dreams',
      description: 'Seeking talented actors for lead and supporting roles in an independent drama about the rebirth of Detroit. This is a paid opportunity with potential for festival exposure. We are looking for authentic performances and diverse representation.',
      roleType: 'LEAD',
      location: 'Detroit, MI',
      compensation: '$800/day + meals',
      submissionDeadline: new Date('2025-11-15'),
      shootingDates: 'January 2026',
      ageRangeMin: 18,
      ageRangeMax: 65,
      gender: 'ANY',
      ethnicity: 'ANY',
      unionStatus: 'EITHER',
      castingEmail: 'casting@motorcitydreams.com',
      status: 'ACTIVE',
    },
    {
      title: 'Commercial - National Car Campaign',
      production: 'Major Automotive Brand',
      description: 'National commercial for a major automotive brand. Looking for real people, not models. Must be comfortable on camera and able to improvise. This will air nationally across multiple platforms.',
      roleType: 'COMMERCIAL',
      location: 'Los Angeles, CA',
      compensation: '$2,500 session fee + usage',
      submissionDeadline: new Date('2025-10-25'),
      shootingDates: 'November 15-16, 2025',
      ageRangeMin: 30,
      ageRangeMax: 50,
      gender: 'ANY',
      ethnicity: 'ANY',
      unionStatus: 'SAG_AFTRA',
      castingEmail: 'automotive.casting@agency.com',
      status: 'ACTIVE',
    },
    {
      title: 'Supporting Role - Netflix Series',
      production: 'Untitled Drama Series',
      description: 'Recurring supporting role for new Netflix drama series. Character is a tech entrepreneur navigating the startup world. Must be comfortable with fast-paced dialogue and ensemble cast work.',
      roleType: 'SUPPORTING',
      location: 'New York, NY',
      compensation: '$1,200/day (episodic rate)',
      submissionDeadline: new Date('2025-10-30'),
      shootingDates: 'December 2025 - March 2026',
      ageRangeMin: 28,
      ageRangeMax: 38,
      gender: 'FEMALE',
      ethnicity: 'ANY',
      unionStatus: 'SAG_AFTRA',
      castingEmail: 'series.casting@netflix.com',
      status: 'ACTIVE',
    },
    {
      title: 'Background Actors - Period Drama',
      production: 'The Gilded Age - Season 3',
      description: 'HBO series seeking background actors for period drama set in 1880s New York. Must be comfortable in period costume. Various roles available including servants, party guests, and street pedestrians.',
      roleType: 'BACKGROUND',
      location: 'New York, NY',
      compensation: '$150/day + overtime',
      submissionDeadline: new Date('2025-11-01'),
      shootingDates: 'Ongoing through February 2026',
      ageRangeMin: 18,
      ageRangeMax: 70,
      gender: 'ANY',
      ethnicity: 'WHITE',
      unionStatus: 'EITHER',
      castingEmail: 'gildedage.extras@hbo.com',
      status: 'ACTIVE',
    },
    {
      title: 'Lead - Romantic Comedy Feature',
      production: 'Love in the City',
      description: 'Female lead for romantic comedy feature film. Character is a witty, career-driven woman who rediscovers love. Must have strong comedic timing and chemistry with male lead. Studio picture with major distribution.',
      roleType: 'LEAD',
      location: 'Chicago, IL',
      compensation: '$5,000/week (4 week shoot)',
      submissionDeadline: new Date('2025-10-28'),
      shootingDates: 'January - February 2026',
      ageRangeMin: 25,
      ageRangeMax: 35,
      gender: 'FEMALE',
      ethnicity: 'ANY',
      unionStatus: 'SAG_AFTRA',
      castingEmail: 'romcom.casting@studio.com',
      status: 'ACTIVE',
    },
    {
      title: 'Commercial - Fast Food Chain',
      production: 'National Restaurant Campaign',
      description: 'Casting real families for national fast food commercial. Looking for authentic, relatable people. Must be comfortable eating on camera and taking direction. Family units preferred but will see individuals.',
      roleType: 'COMMERCIAL',
      location: 'Atlanta, GA',
      compensation: '$1,500/day + residuals',
      submissionDeadline: new Date('2025-10-22'),
      shootingDates: 'November 5-6, 2025',
      ageRangeMin: 8,
      ageRangeMax: 55,
      gender: 'ANY',
      ethnicity: 'DIVERSE',
      unionStatus: 'SAG_AFTRA',
      castingEmail: 'food.commercial@casting.com',
      status: 'ACTIVE',
    },
    {
      title: 'Supporting - Horror Feature',
      production: 'The Haunting of Blackwood Manor',
      description: 'Supporting role in supernatural horror film. Character is a skeptical paranormal investigator. Must be comfortable with practical effects and working nights. Independent feature with theatrical distribution.',
      roleType: 'SUPPORTING',
      location: 'New Orleans, LA',
      compensation: '$600/day',
      submissionDeadline: new Date('2025-11-05'),
      shootingDates: 'December 2025',
      ageRangeMin: 30,
      ageRangeMax: 45,
      gender: 'MALE',
      ethnicity: 'ANY',
      unionStatus: 'NON_UNION',
      castingEmail: 'horror.casting@blackwood.com',
      status: 'ACTIVE',
    },
    {
      title: 'Extra - Action Blockbuster',
      production: 'Untitled Superhero Sequel',
      description: 'Background extras needed for major superhero film. Various roles including city pedestrians, office workers, and party guests. Multiple shoot dates available. Must be flexible with schedule.',
      roleType: 'EXTRA',
      location: 'Los Angeles, CA',
      compensation: '$120/day',
      submissionDeadline: new Date('2025-10-20'),
      shootingDates: 'October - December 2025',
      ageRangeMin: 18,
      ageRangeMax: 65,
      gender: 'ANY',
      ethnicity: 'ANY',
      unionStatus: 'NON_UNION',
      castingEmail: 'superhero.extras@studio.com',
      status: 'ACTIVE',
    },
    {
      title: 'Lead - Indie Thriller',
      production: 'Breach',
      description: 'Male lead for psychological thriller. Character is a cybersecurity expert caught in a dangerous game. Must be able to convey intelligence and paranoia. This is a character-driven piece requiring nuanced performance.',
      roleType: 'LEAD',
      location: 'Austin, TX',
      compensation: '$3,500/week (3 week shoot)',
      submissionDeadline: new Date('2025-11-10'),
      shootingDates: 'January 2026',
      ageRangeMin: 32,
      ageRangeMax: 42,
      gender: 'MALE',
      ethnicity: 'ANY',
      unionStatus: 'EITHER',
      castingEmail: 'breach.casting@indiefilm.com',
      status: 'ACTIVE',
    },
    {
      title: 'Commercial - Pharmaceutical',
      production: 'Health Awareness Campaign',
      description: 'Real patients needed for pharmaceutical commercial. Must be willing to share personal health journey on camera. Compassionate storytelling opportunity. NDA required.',
      roleType: 'COMMERCIAL',
      location: 'Boston, MA',
      compensation: '$2,000/day',
      submissionDeadline: new Date('2025-10-27'),
      shootingDates: 'November 12, 2025',
      ageRangeMin: 40,
      ageRangeMax: 65,
      gender: 'ANY',
      ethnicity: 'DIVERSE',
      unionStatus: 'EITHER',
      castingEmail: 'health.commercial@agency.com',
      status: 'ACTIVE',
    },
    {
      title: 'Supporting - Coming of Age Drama',
      production: 'Senior Year',
      description: 'Supporting roles for high school drama about friendship and identity. Looking for authentic teen actors. Must be age-appropriate or able to play younger. Sensitive material handled professionally.',
      roleType: 'SUPPORTING',
      location: 'Portland, OR',
      compensation: '$500/day',
      submissionDeadline: new Date('2025-11-08'),
      shootingDates: 'December 2025 - January 2026',
      ageRangeMin: 16,
      ageRangeMax: 22,
      gender: 'ANY',
      ethnicity: 'DIVERSE',
      unionStatus: 'NON_UNION',
      castingEmail: 'senioryear.casting@film.com',
      status: 'ACTIVE',
    },
    {
      title: 'Background - Historical Epic',
      production: '1776',
      description: 'Period film set during American Revolution. Seeking background actors for battle scenes, town halls, and colonial villages. Must be comfortable with period dress and historical reenactment.',
      roleType: 'BACKGROUND',
      location: 'Philadelphia, PA',
      compensation: '$175/day',
      submissionDeadline: new Date('2025-10-25'),
      shootingDates: 'November - December 2025',
      ageRangeMin: 20,
      ageRangeMax: 60,
      gender: 'MALE',
      ethnicity: 'WHITE',
      unionStatus: 'EITHER',
      castingEmail: '1776.extras@historical.com',
      status: 'ACTIVE',
    },
    {
      title: 'Lead - Biographical Drama',
      production: 'The Jazz Singer',
      description: 'Lead role in biographical film about legendary jazz musician. Must have musical ability and strong emotional range. This is a passion project with Oscar potential. Singing and instrument skills required.',
      roleType: 'LEAD',
      location: 'New York, NY',
      compensation: '$7,500/week (6 week shoot)',
      submissionDeadline: new Date('2025-11-12'),
      shootingDates: 'February - March 2026',
      ageRangeMin: 35,
      ageRangeMax: 50,
      gender: 'MALE',
      ethnicity: 'BLACK',
      unionStatus: 'SAG_AFTRA',
      castingEmail: 'jazz.casting@biopic.com',
      status: 'ACTIVE',
    },
    {
      title: 'Commercial - Tech Startup',
      production: 'Innovation Campaign',
      description: 'Young entrepreneurs needed for tech startup commercial. Must embody energy and innovation. Will feature real startup founders telling their stories. Authentic, not scripted.',
      roleType: 'COMMERCIAL',
      location: 'San Francisco, CA',
      compensation: '$1,800/day',
      submissionDeadline: new Date('2025-10-24'),
      shootingDates: 'November 8, 2025',
      ageRangeMin: 22,
      ageRangeMax: 35,
      gender: 'ANY',
      ethnicity: 'DIVERSE',
      unionStatus: 'EITHER',
      castingEmail: 'tech.commercial@startup.com',
      status: 'ACTIVE',
    },
    {
      title: 'Supporting - Mystery Series',
      production: 'Cold Case Files',
      description: 'Recurring supporting role in true crime drama series. Character is a forensic analyst. Must be comfortable with technical dialogue and procedural format. Multi-episode arc.',
      roleType: 'SUPPORTING',
      location: 'Miami, FL',
      compensation: '$900/day',
      submissionDeadline: new Date('2025-11-03'),
      shootingDates: 'January - April 2026',
      ageRangeMin: 28,
      ageRangeMax: 40,
      gender: 'FEMALE',
      ethnicity: 'HISPANIC',
      unionStatus: 'SAG_AFTRA',
      castingEmail: 'coldcase.casting@network.com',
      status: 'ACTIVE',
    },
    {
      title: 'Extra - Wedding Scene',
      production: 'Happily Ever After',
      production: 'Happily Ever After',
      description: 'Wedding guests needed for romantic comedy. Upscale wedding scene. Must provide own formal attire (reimbursed). Fun, energetic atmosphere. Multiple takes expected.',
      roleType: 'EXTRA',
      location: 'Nashville, TN',
      compensation: '$100/day + wardrobe fee',
      submissionDeadline: new Date('2025-10-21'),
      shootingDates: 'November 2, 2025',
      ageRangeMin: 21,
      ageRangeMax: 70,
      gender: 'ANY',
      ethnicity: 'ANY',
      unionStatus: 'NON_UNION',
      castingEmail: 'wedding.extras@romcom.com',
      status: 'ACTIVE',
    },
    {
      title: 'Lead - Sports Drama',
      production: 'The Comeback',
      description: 'Lead role in inspiring sports drama about a fallen athlete\'s redemption. Must be athletic and able to perform own sports sequences. Physical training required before shoot.',
      roleType: 'LEAD',
      location: 'Denver, CO',
      compensation: '$6,000/week (5 week shoot)',
      submissionDeadline: new Date('2025-11-15'),
      shootingDates: 'February - March 2026',
      ageRangeMin: 25,
      ageRangeMax: 35,
      gender: 'MALE',
      ethnicity: 'ANY',
      unionStatus: 'SAG_AFTRA',
      castingEmail: 'sports.casting@drama.com',
      status: 'ACTIVE',
    },
    {
      title: 'Commercial - Insurance Company',
      production: 'Family Protection Campaign',
      description: 'Real families needed for insurance commercial focusing on life\'s important moments. Warm, authentic storytelling. Multi-generational families preferred.',
      roleType: 'COMMERCIAL',
      location: 'Dallas, TX',
      compensation: '$1,200/day + usage',
      submissionDeadline: new Date('2025-10-26'),
      shootingDates: 'November 10, 2025',
      ageRangeMin: 5,
      ageRangeMax: 70,
      gender: 'ANY',
      ethnicity: 'DIVERSE',
      unionStatus: 'EITHER',
      castingEmail: 'insurance.commercial@agency.com',
      status: 'ACTIVE',
    },
    {
      title: 'Supporting - Sci-Fi Series',
      production: 'Quantum Leap',
      description: 'Guest star role in established sci-fi series. Character is an alien diplomat. Prosthetics required. Must be comfortable with long makeup sessions and green screen work.',
      roleType: 'SUPPORTING',
      location: 'Vancouver, BC',
      compensation: '$1,100/day',
      submissionDeadline: new Date('2025-11-07'),
      shootingDates: 'December 2025',
      ageRangeMin: 30,
      ageRangeMax: 55,
      gender: 'ANY',
      ethnicity: 'ANY',
      unionStatus: 'ACTRA',
      castingEmail: 'scifi.casting@network.com',
      status: 'ACTIVE',
    },
    {
      title: 'Background - Concert Scene',
      production: 'Rock Legend',
      description: 'Concert audience members needed for biographical film about rock band. Must be enthusiastic and willing to be energetic for multiple takes. Period-appropriate wardrobe provided.',
      roleType: 'BACKGROUND',
      location: 'Seattle, WA',
      compensation: '$150/day',
      submissionDeadline: new Date('2025-10-23'),
      shootingDates: 'November 18-20, 2025',
      ageRangeMin: 18,
      ageRangeMax: 45,
      gender: 'ANY',
      ethnicity: 'ANY',
      unionStatus: 'NON_UNION',
      castingEmail: 'concert.extras@biopic.com',
      status: 'ACTIVE',
    },
  ];

  for (const call of castingCalls) {
    await prisma.castingCall.create({
      data: call,
    });
  }

  console.log(`✅ Created ${castingCalls.length} casting calls`);
}

main()
  .catch((e) => {
    console.error('Error seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
