import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  // Create admin user
  const adminPassword = await bcrypt.hash('Admin123!@#', 10);
  const admin = await prisma.user.upsert({
    where: { email: 'admin@castingcompanion.com' },
    update: {},
    create: {
      email: 'admin@castingcompanion.com',
      passwordHash: adminPassword,
      name: 'Admin User',
      role: 'ADMIN',
    },
  });

  console.log('✅ Admin user created:', admin.email);

  // Create 30+ diverse casting calls
  const calls = [
    {
      title: 'Lead Female Role - Feature Film',
      production: 'Blue Horizon',
      description: 'Seeking a talented actress for the lead role in an independent drama film. Character is a strong-willed journalist in her late 20s investigating a corporate scandal.',
      roleType: 'LEAD',
      genderReq: 'FEMALE',
      ageMin: 22,
      ageMax: 30,
      ethnicityReq: 'ANY',
      location: 'Atlanta, GA',
      compensation: '$300/day',
      unionReq: 'EITHER',
      skillsRequired: [],
      shootDates: 'Oct 20-25, 2025',
      castingEmail: 'casting@bluehorizon.com',
      submissionDeadline: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Supporting Male - TV Series',
      production: 'Night Watch',
      description: 'Recurring role for police detective in crime drama series. Looking for experienced actor with strong presence.',
      roleType: 'SUPPORTING',
      genderReq: 'MALE',
      ageMin: 35,
      ageMax: 50,
      ethnicityReq: 'ANY',
      location: 'Los Angeles, CA',
      compensation: '$500/day',
      unionReq: 'SAG_AFTRA',
      skillsRequired: ['Stage Combat'],
      shootDates: 'Nov 1-30, 2025',
      castingEmail: 'casting@nightwatch.tv',
      submissionDeadline: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Background Extras - Commercial',
      production: 'Nike Sports Campaign',
      description: 'Looking for athletic-looking extras for major sports commercial. Must be comfortable with active scenes.',
      roleType: 'BACKGROUND',
      genderReq: 'ANY',
      ageMin: 18,
      ageMax: 40,
      ethnicityReq: 'ANY',
      location: 'Miami, FL',
      compensation: '$150/day',
      unionReq: 'NON_UNION',
      skillsRequired: ['Sports', 'Running'],
      shootDates: 'Oct 15-17, 2025',
      castingEmail: 'extras@nike-commercial.com',
      submissionDeadline: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Lead Male - Indie Film',
      production: 'Desert Dreams',
      description: 'Lead role in desert-set thriller. Character is a former soldier dealing with PTSD. Intense dramatic scenes.',
      roleType: 'LEAD',
      genderReq: 'MALE',
      ageMin: 28,
      ageMax: 38,
      ethnicityReq: 'ANY',
      location: 'Albuquerque, NM',
      compensation: '$400/day',
      unionReq: 'EITHER',
      skillsRequired: ['Stage Combat', 'Driving'],
      shootDates: 'Nov 10-25, 2025',
      castingEmail: 'cast@desertdreams.film',
      submissionDeadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Supporting Female - Web Series',
      production: 'Tech Tales',
      description: 'Supporting role for Silicon Valley web series. Character is a brilliant software engineer with social anxiety.',
      roleType: 'SUPPORTING',
      genderReq: 'FEMALE',
      ageMin: 24,
      ageMax: 32,
      ethnicityReq: 'ASIAN',
      location: 'San Francisco, CA',
      compensation: '$250/day',
      unionReq: 'NON_UNION',
      skillsRequired: [],
      shootDates: 'Dec 1-15, 2025',
      castingEmail: 'casting@techtales.com',
      submissionDeadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Principal - Fast Food Commercial',
      production: 'BurgerKing National Campaign',
      description: 'Looking for energetic talent for national commercial. Must be comfortable with improvisation.',
      roleType: 'COMMERCIAL',
      genderReq: 'ANY',
      ageMin: 25,
      ageMax: 45,
      ethnicityReq: 'ANY',
      location: 'Chicago, IL',
      compensation: '$800/day + usage',
      unionReq: 'SAG_AFTRA',
      skillsRequired: ['Improv'],
      shootDates: 'Oct 22, 2025',
      castingEmail: 'talent@bkcommercial.com',
      submissionDeadline: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Extra - Period Drama',
      production: 'The Gilded Age',
      description: '1920s period drama needs background actors. Must be comfortable in period costume.',
      roleType: 'EXTRA',
      genderReq: 'ANY',
      ageMin: 20,
      ageMax: 70,
      ethnicityReq: 'ANY',
      location: 'New York, NY',
      compensation: '$120/day',
      unionReq: 'NON_UNION',
      skillsRequired: ['Dancing'],
      shootDates: 'Nov 5-20, 2025',
      castingEmail: 'extras@gildedage.com',
      submissionDeadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Lead Non-Binary - Short Film',
      production: 'Identity',
      description: 'Powerful short film about self-discovery. Seeking authentic non-binary actor for emotionally complex role.',
      roleType: 'LEAD',
      genderReq: 'NON_BINARY',
      ageMin: 22,
      ageMax: 35,
      ethnicityReq: 'ANY',
      location: 'Austin, TX',
      compensation: 'Copy, Credit, Meals',
      unionReq: 'NON_UNION',
      skillsRequired: [],
      shootDates: 'Nov 15-17, 2025',
      castingEmail: 'director@identityfilm.com',
      submissionDeadline: new Date(Date.now() + 22 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Supporting Male - Horror Film',
      production: 'Midnight Caller',
      description: 'Horror film needs antagonist. Must be comfortable with special effects makeup and intense scenes.',
      roleType: 'SUPPORTING',
      genderReq: 'MALE',
      ageMin: 30,
      ageMax: 50,
      ethnicityReq: 'WHITE',
      location: 'Portland, OR',
      compensation: '$350/day',
      unionReq: 'EITHER',
      skillsRequired: ['Stage Combat', 'Stunts'],
      shootDates: 'Oct 25-Nov 5, 2025',
      castingEmail: 'casting@midnightcaller.com',
      submissionDeadline: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Lead Female - Romantic Comedy',
      production: 'Love in the City',
      description: 'Romantic comedy lead. Must have great comedic timing and chemistry-read capability.',
      roleType: 'LEAD',
      genderReq: 'FEMALE',
      ageMin: 26,
      ageMax: 34,
      ethnicityReq: 'ANY',
      location: 'Nashville, TN',
      compensation: '$450/day',
      unionReq: 'SAG_AFTRA',
      skillsRequired: ['Singing'],
      shootDates: 'Dec 5-20, 2025',
      castingEmail: 'casting@loveinthecity.com',
      submissionDeadline: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Background - Music Video',
      production: 'Pop Star Music Video',
      description: 'High-energy music video needs diverse background dancers and extras.',
      roleType: 'BACKGROUND',
      genderReq: 'ANY',
      ageMin: 18,
      ageMax: 30,
      ethnicityReq: 'ANY',
      location: 'Los Angeles, CA',
      compensation: '$200/day',
      unionReq: 'NON_UNION',
      skillsRequired: ['Dancing'],
      shootDates: 'Oct 18, 2025',
      castingEmail: 'casting@musicvideo.com',
      submissionDeadline: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Principal Male - Car Commercial',
      production: 'Toyota Highlander Campaign',
      description: 'Father figure for family SUV commercial. Warm, relatable presence needed.',
      roleType: 'COMMERCIAL',
      genderReq: 'MALE',
      ageMin: 35,
      ageMax: 45,
      ethnicityReq: 'ANY',
      location: 'Detroit, MI',
      compensation: '$1000/day + residuals',
      unionReq: 'SAG_AFTRA',
      skillsRequired: ['Driving'],
      shootDates: 'Nov 8, 2025',
      castingEmail: 'casting@toyotaads.com',
      submissionDeadline: new Date(Date.now() + 16 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Supporting Female - Action Film',
      production: 'Strike Force',
      description: 'Action thriller needs skilled actress for fight scenes. Stunt experience required.',
      roleType: 'SUPPORTING',
      genderReq: 'FEMALE',
      ageMin: 25,
      ageMax: 35,
      ethnicityReq: 'ANY',
      location: 'Atlanta, GA',
      compensation: '$600/day',
      unionReq: 'SAG_AFTRA',
      skillsRequired: ['Stage Combat', 'Stunts', 'Martial Arts'],
      shootDates: 'Nov 12-25, 2025',
      castingEmail: 'stunt@strikeforce.com',
      submissionDeadline: new Date(Date.now() + 19 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Lead Male - Documentary Recreation',
      production: 'History Uncovered',
      description: 'Historical figure recreation for documentary series. Must match specific physical type.',
      roleType: 'LEAD',
      genderReq: 'MALE',
      ageMin: 45,
      ageMax: 60,
      ethnicityReq: 'WHITE',
      location: 'Boston, MA',
      compensation: '$400/day',
      unionReq: 'EITHER',
      skillsRequired: [],
      shootDates: 'Dec 1-5, 2025',
      castingEmail: 'casting@historyuncovered.com',
      submissionDeadline: new Date(Date.now() + 26 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Extra - Sports Film',
      production: 'Championship',
      description: 'Basketball movie needs athletes for crowd and team scenes.',
      roleType: 'EXTRA',
      genderReq: 'MALE',
      ageMin: 18,
      ageMax: 30,
      ethnicityReq: 'ANY',
      location: 'Philadelphia, PA',
      compensation: '$140/day',
      unionReq: 'NON_UNION',
      skillsRequired: ['Basketball', 'Sports'],
      shootDates: 'Nov 18-22, 2025',
      castingEmail: 'extras@championship.com',
      submissionDeadline: new Date(Date.now() + 23 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Supporting Female - Thriller Series',
      production: 'Dark Waters',
      description: 'Psychological thriller series. Character is mysterious neighbor with secrets.',
      roleType: 'SUPPORTING',
      genderReq: 'FEMALE',
      ageMin: 30,
      ageMax: 42,
      ethnicityReq: 'ANY',
      location: 'Seattle, WA',
      compensation: '$550/day',
      unionReq: 'SAG_AFTRA',
      skillsRequired: [],
      shootDates: 'Dec 10-20, 2025',
      castingEmail: 'casting@darkwaters.tv',
      submissionDeadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Principal - Tech Commercial',
      production: 'Apple Product Launch',
      description: 'Major tech product commercial. Looking for diverse, modern talent.',
      roleType: 'COMMERCIAL',
      genderReq: 'ANY',
      ageMin: 22,
      ageMax: 40,
      ethnicityReq: 'ANY',
      location: 'San Francisco, CA',
      compensation: '$1500/day + usage',
      unionReq: 'SAG_AFTRA',
      skillsRequired: [],
      shootDates: 'Nov 20, 2025',
      castingEmail: 'talent@appleads.com',
      submissionDeadline: new Date(Date.now() + 17 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Lead Female - Indie Drama',
      production: 'Quiet Storm',
      description: 'Intimate character study about grief and healing. Requires nuanced performance.',
      roleType: 'LEAD',
      genderReq: 'FEMALE',
      ageMin: 40,
      ageMax: 55,
      ethnicityReq: 'BLACK',
      location: 'New Orleans, LA',
      compensation: '$350/day',
      unionReq: 'EITHER',
      skillsRequired: [],
      shootDates: 'Nov 28-Dec 10, 2025',
      castingEmail: 'director@quietstorm.film',
      submissionDeadline: new Date(Date.now() + 24 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Background - Restaurant Scene',
      production: 'Fine Dining',
      description: 'Upscale restaurant scene needs sophisticated background actors.',
      roleType: 'BACKGROUND',
      genderReq: 'ANY',
      ageMin: 25,
      ageMax: 65,
      ethnicityReq: 'ANY',
      location: 'New York, NY',
      compensation: '$130/day + meals',
      unionReq: 'NON_UNION',
      skillsRequired: [],
      shootDates: 'Oct 21, 2025',
      castingEmail: 'bg@finedining.com',
      submissionDeadline: new Date(Date.now() + 11 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Supporting Male - Western',
      production: 'Dust and Blood',
      description: 'Period Western needs grizzled cowboy type. Horseback riding required.',
      roleType: 'SUPPORTING',
      genderReq: 'MALE',
      ageMin: 40,
      ageMax: 60,
      ethnicityReq: 'WHITE',
      location: 'Santa Fe, NM',
      compensation: '$450/day',
      unionReq: 'SAG_AFTRA',
      skillsRequired: ['Horseback Riding', 'Stage Combat'],
      shootDates: 'Dec 2-12, 2025',
      castingEmail: 'casting@dustandblood.com',
      submissionDeadline: new Date(Date.now() + 27 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Lead Male - Sci-Fi Series',
      production: 'Quantum Leap',
      description: 'Lead role in new sci-fi streaming series. Physicist who travels through time.',
      roleType: 'LEAD',
      genderReq: 'MALE',
      ageMin: 28,
      ageMax: 38,
      ethnicityReq: 'ANY',
      location: 'Vancouver, BC',
      compensation: '$700/day',
      unionReq: 'SAG_AFTRA',
      skillsRequired: [],
      shootDates: 'Jan 15-Mar 30, 2026',
      castingEmail: 'casting@quantumleap.tv',
      submissionDeadline: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Principal Female - Pharmaceutical Commercial',
      production: 'Health First Campaign',
      description: 'Medical commercial needs warm, trustworthy presence. Doctor or patient types.',
      roleType: 'COMMERCIAL',
      genderReq: 'FEMALE',
      ageMin: 35,
      ageMax: 50,
      ethnicityReq: 'ANY',
      location: 'Dallas, TX',
      compensation: '$900/day + residuals',
      unionReq: 'SAG_AFTRA',
      skillsRequired: [],
      shootDates: 'Nov 14, 2025',
      castingEmail: 'casting@healthfirst.com',
      submissionDeadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Extra - Concert Scene',
      production: 'Music Biopic',
      description: '1980s concert scene needs period-appropriate extras. Big hair welcome!',
      roleType: 'EXTRA',
      genderReq: 'ANY',
      ageMin: 18,
      ageMax: 50,
      ethnicityReq: 'ANY',
      location: 'Los Angeles, CA',
      compensation: '$150/day',
      unionReq: 'NON_UNION',
      skillsRequired: [],
      shootDates: 'Nov 25, 2025',
      castingEmail: 'extras@musicbiopic.com',
      submissionDeadline: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Supporting Female - Legal Drama',
      production: 'Justice Served',
      description: 'Courthouse drama series. Character is ambitious prosecutor.',
      roleType: 'SUPPORTING',
      genderReq: 'FEMALE',
      ageMin: 32,
      ageMax: 45,
      ethnicityReq: 'ANY',
      location: 'Chicago, IL',
      compensation: '$600/day',
      unionReq: 'SAG_AFTRA',
      skillsRequired: [],
      shootDates: 'Dec 8-18, 2025',
      castingEmail: 'casting@justiceserved.tv',
      submissionDeadline: new Date(Date.now() + 29 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Lead Male - Horror Anthology',
      production: 'Tales from the Dark',
      description: 'Horror anthology series. Episode lead dealing with supernatural events.',
      roleType: 'LEAD',
      genderReq: 'MALE',
      ageMin: 25,
      ageMax: 40,
      ethnicityReq: 'HISPANIC',
      location: 'Miami, FL',
      compensation: '$500/day',
      unionReq: 'EITHER',
      skillsRequired: [],
      shootDates: 'Nov 22-26, 2025',
      castingEmail: 'casting@talesfromthedark.com',
      submissionDeadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Background - Festival Scene',
      production: 'Summer Nights',
      description: 'Summer music festival scene. Looking for energetic young adults.',
      roleType: 'BACKGROUND',
      genderReq: 'ANY',
      ageMin: 18,
      ageMax: 28,
      ethnicityReq: 'ANY',
      location: 'Austin, TX',
      compensation: '$140/day',
      unionReq: 'NON_UNION',
      skillsRequired: [],
      shootDates: 'Oct 24-25, 2025',
      castingEmail: 'bg@summernights.com',
      submissionDeadline: new Date(Date.now() + 13 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Principal - Insurance Commercial',
      production: 'SafeGuard Insurance',
      description: 'Family-focused insurance commercial. Need real parent energy.',
      roleType: 'COMMERCIAL',
      genderReq: 'ANY',
      ageMin: 30,
      ageMax: 45,
      ethnicityReq: 'ANY',
      location: 'Atlanta, GA',
      compensation: '$800/day + usage',
      unionReq: 'SAG_AFTRA',
      skillsRequired: [],
      shootDates: 'Nov 16, 2025',
      castingEmail: 'talent@safeguard.com',
      submissionDeadline: new Date(Date.now() + 19 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Supporting Male - Coming of Age',
      production: 'First Summer',
      description: 'Teen coming-of-age film. Character is supportive older brother figure.',
      roleType: 'SUPPORTING',
      genderReq: 'MALE',
      ageMin: 20,
      ageMax: 28,
      ethnicityReq: 'ANY',
      location: 'Portland, OR',
      compensation: '$300/day',
      unionReq: 'NON_UNION',
      skillsRequired: ['Driving'],
      shootDates: 'Dec 15-22, 2025',
      castingEmail: 'casting@firstsummer.com',
      submissionDeadline: new Date(Date.now() + 31 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Lead Female - Political Thriller',
      production: 'Capitol Games',
      description: 'Congressional thriller. Lead is determined investigative journalist.',
      roleType: 'LEAD',
      genderReq: 'FEMALE',
      ageMin: 32,
      ageMax: 42,
      ethnicityReq: 'ANY',
      location: 'Washington, DC',
      compensation: '$650/day',
      unionReq: 'SAG_AFTRA',
      skillsRequired: [],
      shootDates: 'Jan 8-28, 2026',
      castingEmail: 'casting@capitolgames.com',
      submissionDeadline: new Date(Date.now() + 33 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Extra - Wedding Scene',
      production: 'Forever Yours',
      description: 'Romantic comedy wedding scene. Need elegant extras for reception.',
      roleType: 'EXTRA',
      genderReq: 'ANY',
      ageMin: 25,
      ageMax: 70,
      ethnicityReq: 'ANY',
      location: 'Charleston, SC',
      compensation: '$125/day',
      unionReq: 'NON_UNION',
      skillsRequired: [],
      shootDates: 'Nov 30, 2025',
      castingEmail: 'extras@foreveryours.com',
      submissionDeadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
    },
    {
      title: 'Principal Male - Beer Commercial',
      production: 'Craft Brew Campaign',
      description: 'Craft beer commercial needs authentic, rugged male presence.',
      roleType: 'COMMERCIAL',
      genderReq: 'MALE',
      ageMin: 28,
      ageMax: 40,
      ethnicityReq: 'ANY',
      location: 'Denver, CO',
      compensation: '$900/day + usage',
      unionReq: 'SAG_AFTRA',
      skillsRequired: [],
      shootDates: 'Nov 19, 2025',
      castingEmail: 'casting@craftbrew.com',
      submissionDeadline: new Date(Date.now() + 17 * 24 * 60 * 60 * 1000),
    },
  ];

  await prisma.castingCall.createMany({
    data: calls,
  });

  console.log(`✅ Created ${calls.length} casting calls`);

  // Optional: Create test actor with profile for demo
  const testActorPassword = await bcrypt.hash('Actor123!', 10);
  const testActor = await prisma.user.create({
    data: {
      email: 'actor@test.com',
      passwordHash: testActorPassword,
      name: 'Jane Actor',
      role: 'ACTOR',
      subStatus: 'ACTIVE',
      profile: {
        create: {
          phone: '+1234567890',
          locationCity: 'Atlanta',
          locationState: 'GA',
          locationZip: '30301',
          age: 28,
          gender: 'FEMALE',
          ethnicity: 'ANY',
          unionStatus: 'EITHER',
          playableAgeMin: 22,
          playableAgeMax: 32,
          roleInterests: ['LEAD', 'SUPPORTING'],
          specialSkills: ['Stage Combat', 'Singing'],
          transportation: true,
          compPrefs: 'Day rate preferred',
          travelWillingness: true,
        },
      },
    },
  });

  console.log('✅ Test actor created:', testActor.email, '(password: Actor123!)');
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
